import "./styles.scss";
import React, { createContext } from "react";
import ReactDOM from "react-dom";
import { useInterpret, useMachine } from "@xstate/react";
import { checkoutMachine } from "./checkoutMachine";
import { Checkout } from "./Checkout";
import { CheckoutSteps } from "./CheckoutSteps";
import { CheckoutStates } from "./CheckoutStates";
import { checkoutScenarios } from "./checkoutScenarios";
import { inspect } from "@xstate/inspect";

inspect({ iframe: false, url: "https://stately.ai/viz?inspect" });

function findScenario(predicate) {
  return Object.values(checkoutScenarios).find(predicate);
}

// Change the scenario here!
export const confirmScenario = findScenario((scenario) =>
  scenario.state.matches("confirmation")
);

export const confirmPaths = confirmScenario.paths;

export function getMeta(state) {
  const keys = Object.keys(state.meta);
  return state.meta[keys[0]];
}

export const CheckoutContext = createContext();

function App() {
  const service = useInterpret(checkoutMachine, {
    devTools: true
  });

  return (
    <div className="App">
      <h2>Sample checkout app</h2>
      <Checkout checkoutRef={service} />
      <hr />
      <h2>Autogenerated steps:</h2>
      <CheckoutSteps />
      <hr />
      <h2>Autogenerated views:</h2>
      <CheckoutStates />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
